import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FEITO A MÃO DECORAÇÕES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <header className={styles.header}>
        <h1 className={styles.title}>FEITO A MÃO DECORAÇÕES</h1>
        <p className={styles.description}>GERANDO INSPIRAÇÃO</p>
      </header>
      <main className={styles.main}>
        <div>
          <div className={styles.about}>
            <h2>SOBRE</h2>
            <div className={styles.text}>
              A empresa atua no ramo de decorações de materiais recicláveis
              feitas a mão, então materiais que iriam ser descartados viram
              peças utilizadas para decorações, criando uma valorização destes
              utensílios, ajudando o meio ambiente.
            </div>
          </div>
          <div className={styles.img}></div>
          <div>
            <h4>Missão:</h4>
            Democratizar o acesso a arte, e melhorar a qualidade de vida das
            pessoas de classes C, D e E, através da qualificação profissional.
            <br />
            <br />
            <h4>valores:</h4>
            Respeito mútuo| Crescimento sustentável | Qualidade
            <br />
            <br />
            <h4>visão:</h4>
            Igualdade social acessibilidade para todos | Valorização e respeito
            ao cliente | Transparência | Responsabilidade social e ambiental |
          </div>
        </div>
        
      </main>
      <div className={styles.contacts}>

          <div className={styles.card}>
            <span className={styles.logo}>
              <a className={styles.name} href="https://www.instagram.com/feitoamao.decoracoes/">
              <Image src="/instagram.png" alt="" width={30} height={30}/>
              </a>
            </span>
          </div>
          <div className={styles.card}>
            <span className={styles.logo}></span>
            <a className={styles.name}>Whatsapp</a>
          </div>
        </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
